name: Redeploy on AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /home/ec2-user/Discord-bot-project-group-6
            git pull
            mvn package
            sudo systemctl restart typingracebot
